version: '3'
services:
  tmodloader:
    image: 'jacobsmile/tmodloader1.4:latest'
    container_name: 'tmodloader'
    ports:
      - "7777:7777"
    expose:
      - "7777"
    environment:
      # Download the Calamity mod and CalamityMusic mod.
      - "TMOD_AUTODOWNLOAD=2815010161,2908170107,2563309347,2909886416,3238219681,2797518634,2619954303,2669644269"
      # Enable the Calamity mod and CalamityMusic mod.
      - "TMOD_ENABLEDMODS=2815010161,2908170107,2563309347,2909886416,3238219681,2797518634,2619954303,2669644269"
      # Shutdown Message and Autosave Interval (In Minutes)
      - "TMOD_SHUTDOWN_MESSAGE=Goodbye!"
      - "TMOD_AUTOSAVE_INTERVAL=5"
      # Server Settings
      - "TMOD_MOTD=Welcome to my tModLoader Server!"
      - "TMOD_MAXPLAYERS=4"
      # The following world settings are only used when generating a new world.
      - "TMOD_WORLDNAME=Grizzly_world"
      - "TMOD_WORLDSIZE=2"
      - "TMOD_WORLDSEED=not the bees!"
      - "TMOD_DIFFICULTY=3"
      # (Deprecated) If TMOD_USECONFIGFILE is set to "Yes", it is expected to have a serverconfig.txt mapped. The Server Settings above will be ignored.
      - "TMOD_USECONFIGFILE=No"
      - "UPDATE_NOTICE=false"
    env_file: '.env'

    labels:
      - "traefik.tcp.routers.tmodloader.entrypoints=tmodloader"
      - "traefik.tcp.routers.tmodloader.rule=*"
    volumes:
    ##### By default, the below setting will create a data directory on your host where this compose file lives.
      - "./data:/data"
      # Uncomment the below line if you plan to use a mapped config file. 
      # - "/path/to/config/config.txt:/root/terraria-server/serverconfig.txt"
    networks:
      - proxy-internal
networks:
  proxy-internal:
    external: true